name: baddie_app
description: A minimal Tinder-like dating Flutter app scaffold.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  logger: ^2.3.0
  image_picker: ^1.2.1
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  badges: ^3.1.2
  video_player: ^2.8.2
  local_auth: ^3.0.0
  geolocator: ^14.0.2
  cloud_firestore: ^6.1.1
  firebase_auth: ^6.1.3
  record: ^6.1.2
  audioplayers: ^6.5.1
  firebase_storage: ^13.0.5
  firebase_core: ^4.3.0
  flutter_webrtc: ^1.2.1
  permission_handler: ^12.0.1
  firebase_messaging: ^16.1.0
  flutter_local_notifications: ^20.0.0
  provider: ^6.0.5
  vibration: ^3.1.5
  firebase_ui_auth: ^3.0.1
  google_fonts: ^8.0.0
  flutter_animate: ^4.2.0
  glassmorphism: ^3.0.0
  shared_preferences: ^2.2.2
  shared_preferences_web: ^2.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/.gitkeep
    - assets/sounds/ringtone_1.mp3
